---
## some basic bits to get a fresh machine minimally useable
- hosts: all
  roles:



  - role: dock1010
    apps:
    - "/Applications/System Preferences.app"
    - /Applications/Utilities/Terminal.app
    - /Applications/TextMate.app
    - /Applications/Safari.app
    folders:
    - path: ~/src/github.com
      view: grid
    - path: ~/Downloads
      sort: datemodified
      view: grid
