---
## some basic bits to get a fresh machine minimally useable
- hosts: all
  roles:

  - role: computername
    computername: VM
 
  - role: git_config
    git_user_mail: ninja@ninjabong.com
    git_user_name: ninjabong
 
  - role: sshd
    sshd: "on"

  - role: datetime
    time_zone: America/New_York

  - role: desktop_image
    desktop_img_path: "http://static.simpledesktops.com/uploads/desktops/2014/07/29/eamessimple.png"

#  - role: googlefonts
#    fonts:
#      - inconsolata
#      - sourcecodepro

  - role: cask_package
    tap: caskroom/fonts
    packages:
      - font-inconsolata
      - font-source-code-pro

  - role: user_image
    image_name: ninjastar.jpg

  - role: gatekeeper
    gatekeeper: disable

  - role: locatedb
    locatedb: load

  - role: unhide_library

  - role: cask_env_package
    package_name: textmate
    homebrew_cask_opts: --appdir=/Applications

  - role: cask_env_package
    package_name: google-chrome
    homebrew_cask_opts: --appdir=/Applications

  - role: finder_prefs
    # first tab
    show_internal: on
    show_external: true
    show_removeable: on
    show_servers: yes
    new_window: home
    #     new_window_path: /path/to/foo
    always_new: on
    spring_loaded_folders: on
    spring_loaded_delay: 0.33
    # third tab
    sidebar: on
    sidebar_width: 190
    sidebar_devices: on
    sidebar_favorites: on
    sidebar_shared: on
    sidebar_tags: off
    # fourth tab
    show_extensions: on
    extension_warning: off
    trash_warning: off
    trash_securely: off
    search_default: mac

  - role: systemprefs_general
    system_appearance: graphite
    highlight_color: "1.000000 0.874510 0.701961"
    sidebar_icon_size: medium
    scrollbar: Automatic
    scroll_behavior: page
    close_confirms_changes: no
    restore_windows: no
    kb_ui_mode: all
    # Only works for 10.10
    interface_style: Dark


  - role: dock1010
    apps:
    - "/Applications/System Preferences.app"
    - /Applications/Utilities/Terminal.app
    - /Applications/TextMate.app
    - "/Applications/Google Chrome.app"
    folders:
    - path: ~/src/github.com
      view: grid
    - path: ~/Downloads
      sort: datemodified
      view: grid
