---
# tasks/main.yml

# because user module doesn't work on osx
- include: "user_osx.yml"
  when: ansible_system == "Darwin"

- include: "user.yml"
  when: ansible_system != "Darwin"

- include: "pip.yml"

- include: "settings.yml"

- include: "venv.yml"

# because apache2 and service modules doesn't work on osx
- include: "wsgi_osx.yml"
  when: ansible_system == "Darwin"

- include: "wsgi.yml"
  when: ansible_system != "Darwin"
