---
# sal/tasks/main.yml

# because user module doesn't work on osx
- include: "user_osx.yml"
  when: ansible_system == "Darwin"

- include: "user.yml"
  when: ansible_system != "Darwin"

# one task to rule all the OSs
- include: "pip.yml"

- include: "settings.yml"

- include: "venv.yml"

# because each needs it's own individual bits
- include: "wsgi_osx.yml"
  when: ansible_system == "Darwin"

- include: "wsgi_deb.yml"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- include: "wsgi_rhel.yml"
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"
