---
# sal/tasks/main.yml
- hosts: all
  gather_facts: True
  tasks:
  - name: Group hosts dynamically by OS
    group_by: key={{ ansible_os_family }}

- hosts: Darwin
  gather_facts: False
  - include: "user_osx.yml"
  - include: "sal.yml"
  - include: "mysql_osx.yml"
    when: sal_use_mysql == True
  - include: "mysql.yml"
    when: sal_use_mysql == True
  - include: "venv.yml"
  - include: "wsgi_osx.yml"

- hosts: Debian
  gather_facts: False
  - include: "user.yml"
  - include: "sal.yml"
  - include: "mysql_deb.yml"
    when: sal_use_mysql == True
  - include: "mysql.yml"
    when: sal_use_mysql == True
  - include: "venv.yml"
  - include: "wsgi_deb.yml"

- hosts: RedHat
  gather_facts: False
  - include: "user.yml"
  - include: "sal.yml"
  - include: "mysql_rhel.yml"
    when: sal_use_mysql == True
  - include: "mysql.yml"
    when: sal_use_mysql == True
  - include: "venv.yml"
  - include: "wsgi_rhel.yml"
