---
# sal/tasks/mysql_osx.yml
- name: mysql_osx - homebrew install mysql and some deps on OS X
  homebrew: name=mysql

- name: mysql_osx - configure launchd to auto start mysql on OS X
  sudo: True
  copy: src=/usr/local/opt/mysql/homebrew.mxcl.mysql.plist
        dest={{ sal_launchagent_path }}
        owner={{ ansible_user_id }}
        group=staff
        mode=0644

- name: mysql_osx - ensure permissions of sal_env
  sudo: True
  file: path={{ sal_env_path }}
        owner={{ sal_user }}
        group={{ sal_group }}
        state=directory
        recurse=yes

- name: mysql_osx - start mysql server via launchctl on OS X
  sudo: True
  command: /bin/launchctl load {{ sal_launchagent_path }}
