---
# sal/tasks/mysql_rhel.yml

- name: yum install mysql and some deps on RHEL/CentOS
  sudo: True
  yum: name={{ item }}
  with_items:
    - "mysql-server"
    - "mysql-client"
    - "mysql-devel"
    - "MySQL-python"

- name: ensure mysql server starts at boot and is running on RHEL/CentOS
  sudo: True
  command: /sbin/systemctl {{ item }} mysqld
  with_items:
    - enable
    - start
