---
# sal/tasks/mysql_rhel.yml
- name: mysql_rhel - yum install mysql and some deps on RHEL/CentOS
  sudo: True
  yum: name={{ item }}
  with_items:
    - "mysql-server"
    - "mysql-client"
    - "mysql-devel"
    - "MySQL-python"

- name: mysql_rhel - ensure mysql server starts at boot and is running on RHEL/CentOS
  sudo: True
  command: /sbin/systemctl {{ item }} mysqld
  with_items:
    - enable
    - start

- name: mysql_rhel - run mysql_secure_installation
  sudo: True
  command: /usr/bin/mysql_secure_installation
