---
# sal/tasks/mysql_osx.yml
# mysql is a permissions mess, percona "just works"
- name: mysql_osx - homebrew install percona mysql server and some deps on OS X
  homebrew: name=percona-server

- name: mysql_osx - ensure ~/Library/LaunchAgents exists
  file: path=~/Library/LaunchAgents
        owner={{ ansible_user_id }}
        group=staff
        mode=0755
        state=directory

- name: mysql_osx - configure launchd to auto start mysql on OS X
  sudo: True
  copy: src=/usr/local/opt/percona-server/homebrew.mxcl.percona-server.plist
        dest={{ sal_launchagent_path }}
        owner={{ ansible_user_id }}
        group=staff
        mode=0755

- name: mysql_osx - ensure permissions of sal_env
  sudo: True
  file: path={{ sal_env_path }}
        owner={{ sal_user }}
        group={{ sal_group }}
        state=directory
        recurse=yes

- name: mysql_osx - start mysql server via launchctl on OS X
  command: /bin/launchctl load {{ sal_launchagent_path }}
