---
# sal/tasks/mysql_osx.yml
- name: mysql_osx - homebrew install mysql and some deps on OS X
#  homebrew: name=mysql
# mysql is a mess of permissions?
  homebrew: name=percona-server

#- name: mysql_osx - fix permissions for mysql dir
#  sudo: True
#  file: path=/usr/local/var/mysql
#        owner=mysql
#        group=staff
#        state=directory
#        mode=0775
#        recurse=yes

- name: mysql_osx - configure launchd to auto start mysql on OS X
  sudo: True
#  copy: src=/usr/local/opt/mysql/homebrew.mxcl.mysql.plist
  copy: src=/usr/local/opt/percona-server/homebrew.mxcl.percona-server.plist
        dest={{ sal_launchagent_path }}
        state=link
        owner={{ ansible_user_id }}
        group=staff
        mode=0755

- name: mysql_osx - ensure permissions of sal_env
  sudo: True
  file: path={{ sal_env_path }}
        owner={{ sal_user }}
        group={{ sal_group }}
        state=directory
        recurse=yes

- name: mysql_osx - start mysql server via launchctl on OS X
  sudo: True
  command: /bin/launchctl load {{ sal_launchagent_path }}
