---
# sal/tasks/mysql_deb.yml
- name: mysql_deb - apt-get install mysql and some deps on Debian/Ubuntu
  sudo: True
  apt: name={{ item }}
  with_items:
    - "mysql-server"
    - "mysql-client"
    - "build-dep"
    - "python-mysqldb"

- name: mysql_deb - ensure mysql server starts at boot and is running on Debian/Ubuntu
  sudo: True
  command: /usr/sbin/update-rc.d mysql defaults

- name: mysql_deb - (re)start mysql server for Debian/Ubuntu
  sudo: True
  service: name=mysql state=reloaded
