---
# sal/tasks/prereqs_rhel.yml

- name: install the 'Development tools' package group
  sudo: True
  yum: name="@Development tools"

- name: install libffi and openssl development libraries
  sudo: True
  yum: "name={{ item }} "
  with_items:
    - libffi-devel
    - openssl-devel
