---
# sal/tasks/user.yml
- name: create sal user and group for OS X
  sudo: True
  command: /usr/bin/dscl . {{ item }}
  with_items:
    - '-create /Groups/{{ sal_group }}'
    - '-create /Groups/{{ sal_group }} PrimaryGroupID "303"'
    - '-create /Users/{{ sal_user }}'
    - '-create /Users/{{ sal_user }} UserShell /bin/bash'
    - '-create /Users/{{ sal_user }} UniqueID "303"'
    - '-create /Users/{{ sal_user }} NFSHomeDirectory {{ sal_env_path }}'
    - '-create /Users/{{ sal_user }} PrimaryGroupID "303"'
  when: ansible_system == "Darwin"
