---
# sal/tasks/user.yml
- name: user - create sal group for non-OS X
  sudo: True
  user: name={{ sal_group }}

- name: user - create sal user for non-OS X
  sudo: True
  user: name={{ sal_user }}
        group={{ sal_group }}
        append=yes
        shell=/bin/bash
