---
# sal/tasks/user.yml
- name: create sal group for non-OS X
  sudo: True
  user: name={{ sal_group }}
  when: ansible_system != "Darwin"

- name: create sal user for non-OS X
  sudo: True
  user: name={{ sal_user }}
        group={{ sal_group }}
        append=yes
        shell=/bin/bash
  when: ansible_system != "Darwin"
