---
# sal/tasks/wsgi_osx.yml
- name: wsgi_osx - check if OS X Client or Server
  stat: path=/Library/Server/Web/Data/Sites/Default
  register: is_osx_server

- name: wsgi_osx - pip install mod_wsgi on OS X Client
  sudo: True
  pip: name=mod_wsgi
  when: is_osx_server.stat.exists == false

- name: wsgi_osx - copy mod_wsgi to apache2 module's dir on OS X Client
  sudo: True
  copy: src=/Library/Python/2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so
        dest=/usr/libexec/apache2/mod_wsgi.so
        owner=root
        group=wheel
        mode=0755
  when: is_osx_server.stat.exists == false

- name: wsgi_osx - enable mod_wsgi module on OS X Client
  sudo: True
  lineinfile: dest=/private/etc/apache2/httpd.conf
              insertafter='LoadModule hfs_apple_module'
              line='LoadModule wsgi_module libexec/apache2/mod_wsgi.so'
  when: is_osx_server.stat.exists == false

- name: wsgi_osx - copy vhost template for apache2 on OS X
  sudo: True
  template: src=sal_vhost.conf.j2
            dest=/private/etc/apache2/other/sal.conf
            owner=root
            group=wheel
            mode=0644
  when: is_osx_server.stat.exists == false

- name: wsgi_osx - fix vhost template for apache2 on OS X Client pre 10.10
  sudo: True
  lineinfile: dest=/etc/apache2/other/sal.conf
              state=absent
              regexp='^       Require all granted'
  when: "is_osx_server.stat.exists == false and ansible_distribution_version | search('10.[8|9]')"

- name: wsgi_osx - fix vhost template for apache2 on OS X Server pre 10.10
  sudo: True
  lineinfile: dest=/Library/Server/Web/Config/apache2/other/sal.conf
              state=absent
              regexp='^       Require all granted'
  when: "is_osx_server.stat.exists == false and ansible_distribution_version | search('10.[8|9]')"

- name: wsgi_osx - symlink {{ sal_env_path }} to apache2s default DocumentRoot on OS X Client
  sudo: True
  file: src={{ sal_env_path }}
        dest=/Library/Webserver/Documents/{{ sal_env_path | basename }}
        owner=root group=wheel
        state=link
  when: is_osx_server.stat.exists == false

- name: wsgi_osx - symlink {{ sal_env_path }} to apache2s default DocumentRoot on OS X Server
  sudo: True
  file: src={{ sal_env_path }}
        dest=/Library/Server/Web/Data/Sites/Default/{{ sal_env_path | basename }}
        owner=root group=wheel
        state=link
  when: is_osx_server.stat.exists == true

- name: wsgi_osx - (re)start apache2 on OS X Client
  sudo: True
  command: /usr/sbin/apachectl restart
  when: is_osx_server.stat.exists == false

- name: wsgi_osx - stop apache2 on OS X Server
  sudo: True
  command: /Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin stop web
  when: is_osx_server.stat.exists == true

- name: wsgi_osx - start apache2 on OS X Server
  sudo: True
  command: /Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin start web
  when: is_osx_server.stat.exists == true
