---
# sal/tasks/wsgi_rhel.yml
- name: ensure apache2 and mod_wsgi are installed for RHEL/CentOS
  sudo: True
  yum: name={{ item }}
  with_items:
    - httpd
    - httpd-devel
    - python-devel
    - mod_wsgi
    - libselinux-python
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"

# doesn't work?
#- name: enable apache2's wsgi module for non-OS X
#  apache2_module: name=mod_wsgi state=present

- name: copy vhost template for apache2 for RedHat/CentOS
  sudo: True
  template: src=sal_vhost.j2
            dest=/etc/httpd/conf.d/sal.conf
            owner=root
            group=wheel
            mode=0644
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"

# comment out <Directory /> lines in:
# rhel/centos = /etc/httpd/conf/httpd.conf

- name: disable selinux
  selinux: state=disabled

- name: enable port 80 in firewall
  sudo: True
  command: firewall-cmd {{ item }}
  with_items: 
    - "--zone=public --add-port=80/tcp --permanent"
    - "--reload"
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"

- name: enable and start apache2
  sudo: True
  command: systemctl {{ item }} httpd
  with_items:
    - enable
    - start
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"

# doesn't work?
#- name: (re)start apache2 for non-OS X
#  sudo: True
#  service: name=httpd state=reloaded
