---
# sal/tasks/wsgi_deb.yml
- name: wsgi_deb - ensure apache2 and mod_wsgi are installed on Debian/Ubuntu
  sudo: True
  apt: name={{ item }}
  with_items:
    - apache2
    - apache2-dev
    - python-dev
    - libapache2-mod-wsgi
    - python-selinux

- name: wsgi_deb - copy vhost template for apache2 on Debian/Ubuntu
  sudo: True
  template: src=sal_vhost.conf.j2
            dest="/etc/apache2/sites-available/sal.conf"
            owner=root
            group=root
            mode=0644

- name: wsgi_deb - check existence of /etc/selinux/config on Debian/Ubuntu
  stat: path=/etc/selinux/config
  register: selinux_cfg

- name: wsgi_deb - disable selinux on Debian/Ubuntu
  selinux: state=disabled
  when: selinux_cfg.stat.exists == True

- name: wsgi_deb - disable 000-default.conf for apache2 on Debian/Ubuntu
  sudo: True
  file: path=/etc/apache2/sites-enabled/000-default.conf
        state=absent

- name: wsgi_deb - enable sal.conf for apache2 on Debian/Ubuntu
  sudo: True
  file: src=/etc/apache2/sites-available/sal.conf
        dest=/etc/apache2/sites-enabled/sal.conf
        state=link
        owner=root
        group=root

- name: wsgi_deb - (re)start apache2 for Debian/Ubuntu
  sudo: True
  service: name=apache2 state=reloaded
