---

- name: pip install mod_wsgi for non-OS X
  sudo: True
  pip: name=mod_wsgi

- name: enable apache2's wsgi module for non-OS X
  apache2_module: name=wsgi state=present

- name: copy vhost template for apache2 for RedHat/CentOS
  sudo: True
  template: src=sal_vhost.j2
            dest=/etc/httpd/conf.d/sal.conf
            owner=root
            group=wheel
            mode=0644
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"

- name: copy vhost template for apache2 for Debian/Ubuntu
  sudo: True
  template: src=sal_vhost.j2
            dest="/etc/apache2/sites-available/sal.conf"
            owner=root
            group=wheel
            mode=0644
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: (re)start apache2 for non-OS X
  sudo: True
  service: name=httpd state=reloaded
