---
- hosts: all
  roles:

  - role: finder_prefs
	# first tab
    show_internal: on
    show_external: true
    show_removeable: on
    show_servers: yes
    new_window: home
    #     new_window_path: /path/to/foo
    always_new: on
    spring_loaded_folders: on
    spring_loaded_delay: 0.33
    # third tab
    sidebar: on
    sidebar_width: 190
    sidebar_devices: on
    sidebar_favorites: on
    sidebar_shared: on
    sidebar_tags: off
    # fourth tab
    show_extensions: on
    extension_warning: off
    trash_warning: off
    trash_securely: off
    search_default: mac
