---
- hosts: all

  vars_prompt:
    - name: "sal_db_passwd"
      prompt: "passwd for sal's db admin / weblogin"
      private: yes
      confirm: yes

  roles:

  - role: sal
    sal_env_path: /Users/Shared/sal_env
    sal_db_admin: sal
    sal_db_email: sal@sal.sal
