---
- hosts: all

  vars_prompt:
#    - name: sal_db_admin
#      prompt: "name for sal's db admin / weblogin"
#      default: sal

    - name: "sal_db_passwd"
      prompt: "passwd for sal's db admin / weblogin"
      private: yes
#      encrypt: "sha256_crypt"
      confirm: yes
#      salt_size: 7

  roles:

  - role: sal
    sal_env_path: /Users/Shared/sal_env
    sal_db_admin: sal
    sal_db_email: sal@sal.sal
