---
- hosts: all
  roles:

  - role: cask_package
    tap: caskroom/fonts
    packages:
      - font-inconsolata
      - font-source-code-pro

  # install some Terminal.app prefs
  - role: terminal_prefs
    startup_theme: mypro
    default_theme: mybrew
